name: Daily Sync Fork

# 触发条件
on:
  schedule:
    # 每天北京时间早上 8:00 执行同步 (UTC时间 0:00)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许你在网页上手动点击运行

jobs:
  build: # 或者你命名的其他任务名
    runs-on: ubuntu-latest
    # 必须加上下面这两行授权：
    permissions:
      contents: write
    steps:
      - name: Sync Fork
        # 使用 GitHub 官方命令行工具进行同步，默认同步 master 分支
        run: gh repo sync $GITHUB_REPOSITORY --branch master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
